apiVersion: v1
kind: Service
metadata:
  name: chess-battle-web-lb
  namespace: chess-battle
  labels:
    app: chess-battle-web
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "chess-battle-web"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: chess-battle-web
---
apiVersion: v1
kind: Service
metadata:
  name: chess-battle-websocket-lb
  namespace: chess-battle
  labels:
    app: chess-battle-websocket
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "chess-battle-websocket"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
    # Enable proxy protocol for websocket sticky sessions
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3002
    protocol: TCP
    name: websocket
  selector:
    app: chess-battle-websocket
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
